# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '项目框架 - by Candy' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 项目框架 - by Candy

  target '项目框架 - by CandyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '项目框架 - by CandyUITests' do
    inherit! :search_paths
    # Pods for testing
  end
#网络请求
pod 'AFNetworking'
#键盘回收管理
pod 'IQKeyboardManager'

end
